apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-postgres
  local:
    path: /k8s-volumes/odoo/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
