apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: ClusterIP
  selector:
    app: app-odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: class-odoo-addons
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: class-odoo-config
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: class-odoo-web-data
reclaimPolicy: Retain
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-addons
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-addons
  local:
    path: /k8s-volumes/odoo/addons
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-addons-replicas2
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-addons
  local:
    path: /k8s-volumes/odoo/addons
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-addons-replicas3
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-addons
  local:
    path: /k8s-volumes/odoo/addons
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-config
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-config
  local:
    path: /k8s-volumes/odoo/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-config-replicas2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-config
  local:
    path: /k8s-volumes/odoo/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-config-replicas3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-config
  local:
    path: /k8s-volumes/odoo/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-data
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-web-data
  local:
    path: /k8s-volumes/odoo/web-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-data-replicas2
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-web-data
  local:
    path: /k8s-volumes/odoo/web-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-data-replicas3
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: class-odoo-web-data
  local:
    path: /k8s-volumes/odoo/web-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - shermine237-latitudee6410
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odoo-statefulset
  labels:
    app: app-odoo
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-odoo
  template:
    metadata:
      name: odoo-pod
      labels:
        app: app-odoo
    spec:
      containers:
        - name: odoo-container
          image: library/odoo:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres-service
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          volumeMounts:
            - mountPath: "/mnt/extra-addons"
              name: pvc-odoo-addons
            - mountPath: "/etc/odoo"
              name: pvc-odoo-config
            - mountPath: "/var/lib/odoo"
              name: pvc-odoo-web-data

  volumeClaimTemplates:
    - metadata:
        name: pvc-odoo-addons
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: class-odoo-addons
    - metadata:
        name: pvc-odoo-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: class-odoo-config
    - metadata:
        name: pvc-odoo-web-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        storageClassName: class-odoo-web-data
