apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odoo-statefulset
  labels:
    app: app-odoo
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-odoo
  template:
    metadata:
      name: odoo-pod
      labels:
        app: app-odoo
    spec:
      containers:
        - name: odoo-container
          image: library/odoo:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres-pod
            - name: USER
              value: odoo
            - name: PASSWORD
              value: myodoo
          volumeMounts:
            - mountPath: "/mnt/extra-addons"
              name: pvc-odoo-addons
            - mountPath: "/etc/odoo"
              name: pvc-odoo-config
            - mountPath: "/var/lib/odoo"
              name: pvc-odoo-web-data

  volumeClaimTemplates:
    - metadata:
        name: pvc-odoo-addons
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: class-odoo-addons
    - metadata:
        name: pvc-odoo-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: class-odoo-config
    - metadata:
        name: pvc-odoo-web-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: class-odoo-web-data
