apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    db_host = postgres-service
    db_port = 5432
    db_user = odoo
    db_password = odoo
    addons_path = /mnt/extra-addons
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: ClusterIP
  selector:
    app: app-odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-addons
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
  ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-web-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: odoo-statefulset
  labels:
    app: app-odoo
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-odoo
  template:
    metadata:
      name: odoo-pod
      labels:
        app: app-odoo
    spec:
      containers:
        - name: odoo-container
          image: library/odoo:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres-service
            - name: USER
              value: odoo
            - name: PASSWORD
              value: odoo
          volumeMounts:
            - name: volume-odoo-addons
              mountPath: "/mnt/extra-addons"
            - name: volume-odoo-web-data
              mountPath: "/var/lib/odoo"
            - name: volume-config
              mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
      volumes:
        - name: volume-odoo-addons
          persistentVolumeClaim:
            claimName: pvc-odoo-addons
        - name: volume-odoo-web-data
          persistentVolumeClaim:
            claimName: pvc-odoo-web-data
        - name: config-volume
          configMap:
            name: odoo-config
